application: slonopass
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: 1.5

builtins:
- django_wsgi: on

skip_files:
- ^env/.*

handlers:
- url: /.*
  script: google.appengine.ext.django.main.app
  secure: always
